name: e2e execution on windows desktop 

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'

jobs:
  windows:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['10']
        windows-featurepack: ['22h2-ent']

    steps:
    - name: Create instance
      run: |
        # Create instance
        podman run -d --name windows-create --rm \
          -v ${PWD}:/workspace:z \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET='${{ secrets.ARM_CLIENT_SECRET }}' \
          quay.io/rhqp/qenvs:v0.0.5 azure \
            windows create \
            --project-name 'windows-desktop' \
            --backed-url 'file:///workspace' \
            --conn-details-output '/workspace' \
            --windows-version '${{ matrix.windows-version }}' \
            --windows-featurepack '${{ matrix.windows-featurepack }}' \
            --vmsize 'Standard_D8s_v4' \
            --tags project=podman-desktop \
            --spot
        # Check logs 
        podman logs -f windows-create

    - name: Check instance system info
      run: |
        ssh -i id_rsa \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ServerAliveInterval=30 \
          -o ServerAliveCountMax=1200 \
          $(cat username)@$(cat host) "systeminfo"

    - name: Emulate X session 
      run: |
        # use fake rdp to emulate an active x session
        podman run -d --name x-session \
          -e RDP_HOST=$(cat host) \
          -e RDP_USER=$(cat username) \
          -e RDP_PASSWORD=$(cat userpassword) \
          quay.io/rhqp/frdp:v0.0.1
        # Wait until the x session has been created
        podman wait --condition running x-session
        # Check logs for the x session
        podman logs x-session

    - name: Install wsl2
      run: |
        # Install wsl2
        echo "Install wsl2"
        ssh -i id_rsa -o StrictHostKeyChecking=no \
                        $(cat username)@$(cat host) "wsl --set-default-version 2"
        ssh -i id_rsa -o StrictHostKeyChecking=no \
                        -o ServerAliveInterval=30 \
                        -o ServerAliveCountMax=1200 \
                        $(cat username)@$(cat host) "wsl --install --no-distribution"
        # Reboot after 
        echo  "Reboot"
        ssh -i id_rsa -o StrictHostKeyChecking=no \
            $(cat username)@$(cat host) "Restart-Computer -Force" &>/dev/null
        # Wait for machine
        while !(nc -z $(cat host) 22 &>/dev/null); do echo "Waiting for machine to come up ..." && sleep 7; done
        
    - name: Run podman desktop e2e
      run: |
        # Get latest built 
        tag=$(curl --silent https://api.github.com/repos/containers/podman-desktop/releases | jq -r 'map(select(.prerelease)) | first | .tag_name')
        # Run e2e tests
        podman run --rm -d --name pd-e2e-windows \
          -e TARGET_HOST=$(cat host) \
          -e TARGET_HOST_USERNAME=$(cat username) \
          -e TARGET_HOST_KEY_PATH=/data/id_rsa \
          -e TARGET_FOLDER=pd-e2e \
          -e TARGET_RESULTS=podman-desktop-e2e-results-${tag}.xml \
          -e OUTPUT_FOLDER=/data \
          -e DEBUG=true \
          -v $PWD:/data:z \
          quay.io/rhqp/podman-desktop-e2e:v1.1.0-windows-amd64  \
              pd-e2e/run.ps1 \
                  -targetFolder pd-e2e \
                  -wslInstallFix 'false' \
                  -pdUrl "https://github.com/containers/podman-desktop/releases/download/${tag}/podman-desktop-${tag:1}.exe" \
                  -junitResultsFilename podman-desktop-e2e-results-${tag}.xml 
        # Check logs 
        podman logs -f pd-e2e-windows

    - name: Run podman functional e2e test
      timeout-minutes: 60
      run: |
        # Get latest built 
        tag=$(curl --silent https://api.github.com/repos/containers/podman-desktop/releases | jq -r 'map(select(.prerelease)) | first | .tag_name')
        # Run e2e tests
        podman run --rm -d --name podman-e2e \
          -e TARGET_HOST=$(cat host) \
          -e TARGET_HOST_USERNAME=$(cat username) \
          -e TARGET_HOST_KEY_PATH=/data/id_rsa \
          -e TARGET_FOLDER=podman-e2e \
          -e TARGET_RESULTS=podman-e2e-results-${tag}.xml \
          -e OUTPUT_FOLDER=/data \
          -e DEBUG=true \
          -v $PWD:/data:z \
          quay.io/rhqp/podman-backend-e2e:v4.7.1-windows-amd64 \
              podman-e2e/run.ps1 \
                  -targetFolder podman-e2e \
                  -podmanStart "true" \
                  -junitResultsFilename podman-e2e-results-${tag}.xml 
        # Check logs 
        podman logs -f podman-e2e

    - name: Upload e2e results
      uses: actions/upload-artifact@v3
      with:
        name: E2E-results-windows-${{ matrix.windows-version }}${{ matrix.windows-featurepack }}
        path: |
          podman-e2e-results-*.xml
          podman-desktop-e2e-results-*.xml

    - name: Destroy instance
      if: always()
      run: |
        # Destroy instance
        podman run -d --name windows-destroy --rm \
          -v ${PWD}:/workspace:z \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET='${{ secrets.ARM_CLIENT_SECRET }}' \
          quay.io/rhqp/qenvs:v0.0.5 azure \
            windows destroy \
            --project-name 'windows-desktop' \
            --backed-url 'file:///workspace'
        # Check logs
        podman logs -f windows-destroy
        
